# Generated by Django 5.2.5 on 2026-05-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='no_prescription_needed',
            field=models.BooleanField(default=False, help_text='Explicitly mark that this encounter does not require any prescriptions.', verbose_name='No Prescription Needed'),
        ),
        migrations.AddField(
            model_name='historicalencounter',
            name='no_prescription_needed',
            field=models.BooleanField(default=False, help_text='Explicitly mark that this encounter does not require any prescriptions.', verbose_name='No Prescription Needed'),
        ),
    ]
