# Generated by Django 5.2.5 on 2026-04-28 05:57

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPatient',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Updated At')),
                ('patient_number', models.CharField(db_index=True, max_length=20, verbose_name='Patient Number')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('estimated_age', models.PositiveSmallIntegerField(blank=True, help_text='Used when date of birth is unknown', null=True, verbose_name='Estimated Age (years)')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, verbose_name='Sex')),
                ('national_id', models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='National ID')),
                ('photo', models.TextField(blank=True, max_length=100, null=True, verbose_name='Photo')),
                ('phone', models.CharField(blank=True, db_index=True, default='', help_text='E.164 format, e.g. +255712345678', max_length=20, verbose_name='Phone')),
                ('village', models.CharField(blank=True, default='', max_length=100, verbose_name='Village')),
                ('ward', models.CharField(blank=True, default='', max_length=100, verbose_name='Ward')),
                ('district', models.CharField(default='Monduli', max_length=100, verbose_name='District')),
                ('region', models.CharField(default='Arusha', max_length=100, verbose_name='Region')),
                ('next_of_kin_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Next of Kin Name')),
                ('next_of_kin_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Next of Kin Phone')),
                ('next_of_kin_relationship', models.CharField(blank=True, default='', max_length=100, verbose_name='Relationship')),
                ('is_pregnant', models.BooleanField(default=False, verbose_name='Pregnant')),
                ('chronic_conditions', models.TextField(blank=True, default='', verbose_name='Chronic Conditions')),
                ('allergies', models.TextField(blank=True, default='', verbose_name='Allergies')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('language_preference', models.CharField(choices=[('sw', 'Kiswahili'), ('en', 'English')], default='sw', max_length=5, verbose_name='Language Preference')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'historical Patient',
                'verbose_name_plural': 'historical Patients',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('patient_number', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Patient Number')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('estimated_age', models.PositiveSmallIntegerField(blank=True, help_text='Used when date of birth is unknown', null=True, verbose_name='Estimated Age (years)')),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, verbose_name='Sex')),
                ('national_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='National ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='patient_photos/%Y/%m/', verbose_name='Photo')),
                ('phone', models.CharField(blank=True, db_index=True, default='', help_text='E.164 format, e.g. +255712345678', max_length=20, verbose_name='Phone')),
                ('village', models.CharField(blank=True, default='', max_length=100, verbose_name='Village')),
                ('ward', models.CharField(blank=True, default='', max_length=100, verbose_name='Ward')),
                ('district', models.CharField(default='Monduli', max_length=100, verbose_name='District')),
                ('region', models.CharField(default='Arusha', max_length=100, verbose_name='Region')),
                ('next_of_kin_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Next of Kin Name')),
                ('next_of_kin_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Next of Kin Phone')),
                ('next_of_kin_relationship', models.CharField(blank=True, default='', max_length=100, verbose_name='Relationship')),
                ('is_pregnant', models.BooleanField(default=False, verbose_name='Pregnant')),
                ('chronic_conditions', models.TextField(blank=True, default='', verbose_name='Chronic Conditions')),
                ('allergies', models.TextField(blank=True, default='', verbose_name='Allergies')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('language_preference', models.CharField(choices=[('sw', 'Kiswahili'), ('en', 'English')], default='sw', max_length=5, verbose_name='Language Preference')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_patients', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated By')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['patient_number'], name='patients_pa_patient_f07fc4_idx'), models.Index(fields=['phone'], name='patients_pa_phone_fc49bb_idx'), models.Index(fields=['national_id'], name='patients_pa_nationa_70cc77_idx'), models.Index(fields=['full_name'], name='patients_pa_full_na_b75abe_idx')],
            },
        ),
    ]
