# Generated by Codex on 2026-05-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="patient_number",
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name="Patient Number"),
        ),
        migrations.AlterField(
            model_name="historicalpatient",
            name="patient_number",
            field=models.CharField(db_index=True, max_length=50, verbose_name="Patient Number"),
        ),
        migrations.AddField(
            model_name="patient",
            name="location",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Reception lookup location, landmark, or directions",
                max_length=255,
                verbose_name="Location",
            ),
        ),
        migrations.AddField(
            model_name="historicalpatient",
            name="location",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Reception lookup location, landmark, or directions",
                max_length=255,
                verbose_name="Location",
            ),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(fields=["location"], name="patients_pa_locatio_fb566c_idx"),
        ),
    ]
