# Generated by Django 5.2.18 on 2026-10-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
