# Generated by Django 5.2.18 on 2026-10-08 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
        ('lab', '0002_labtest_critical_limits'),
        ('pharmacy', '0002_stockmovement_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvoice',
            name='prepay_type',
            field=models.CharField(blank=True, choices=[('', 'Not a prepaid consultation'), ('GENERAL', 'General consultation'), ('MENTAL_HEALTH', 'Mental health consultation')], db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='reverses',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='billing.payment'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='prepay_type',
            field=models.CharField(blank=True, choices=[('', 'Not a prepaid consultation'), ('GENERAL', 'General consultation'), ('MENTAL_HEALTH', 'Mental health consultation')], db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='lab_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='lab.laborder'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='pharmacy.prescription'),
        ),
        migrations.AddField(
            model_name='payment',
            name='reverses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='billing.payment'),
        ),
    ]
